### ISSUE TITLE
pnpm run dev failed: Error: ENAMETOOLONG: name too long, stat 

### ISSUE THREAD

**Issue by fishandsheep** [iluwatar/java-design-patterns-vuepress-web#98]
pnpm version `9.9.0`

```
gitpod /workspace/java-design-patterns-vuepress-web (main) $ pnpm run dev

> java-design-patterns-vuepress-web@2.0.0 dev /workspace/java-design-patterns-vuepress-web
> vuepress dev src

@vuepress/client is no longer needed, you should remove it from deps and change all @vuepress/client imports to vuepress/client
container is deprecated, please use "hint" instead.
imageLazyload is deprecated, please use "imgLazyload" instead.
imageSize is deprecated, please use "imgSize" instead.
imageTitle is deprecated, please use "figure" instead.
vuepress-plugin-md-enhance:  ✖ presentation is no longer supported, please use revealJs instead.
vuepress-plugin-md-enhance:  ✖ Package chart.js is not installed, please install it manually!
vuepress-plugin-md-enhance:  ✖ Package echarts is not installed, please install it manually!
vuepress-plugin-md-enhance:  ✖ Package flowchart.ts is not installed, please install it manually!
vuepress-plugin-md-enhance:  ✖ Package katex is not installed, please install it manually!
vuepress-plugin-md-enhance:  ✖ Package mermaid is not installed, please install it manually!
vuepress-plugin-md-enhance:  ✖ Package reveal.js is not installed, please install it manually!
vuepress-plugin-md-enhance:  ✖ Package @vue/repl is not installed, please install it manually!
vuepress-theme-hope:  ⚠ action is deprecated in README.md frontmatter, please use "actions" instead.
vuepress-theme-hope:  ⚠ shortTitle in frontMatter should be string, found in es/patterns/README.md.
vuepress-theme-hope:  ⚠ action is deprecated in ko/README.md frontmatter, please use "actions" instead.
vuepress-theme-hope:  ⚠ action is deprecated in zh/README.md frontmatter, please use "actions" instead.
vuepress-theme-hope:  ⚠ shortTitle in frontMatter should be string, found in ko/patterns/README.md.
vuepress-theme-hope:  ⚠ shortTitle in frontMatter should be string, found in zh/patterns/README.md.
✔ Initializing and preparing data - done in 9.53s
✔ Compilation finished in 20635ms
success VuePress webpack dev server is listening at http://localhost:8080/
webpack compiled successfully
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: ENAMETOOLONG: name too long, stat 'src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/workspace/java-design-patterns-vuepress-web/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/index.js:647:10)
    at NodeFsHandler._addToNodeFs (/workspace/java-design-patterns-vuepress-web/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:645:18)
    at async /workspace/java-design-patterns-vuepress-web/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0) {
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'stat',
  path: 'src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src/.vuepress/components/src'
}

Node.js v20.17.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by fishandsheep** [comment]
look this https://github.com/iluwatar/java-design-patterns-vuepress-web/pull/99

**Comment by kaizencode-art** [comment]
I encountered the same issue. It was resolved by fixing the path as done in @fishandsheep's PR (no need to modify generate.sh).
@iluwatar, could you provide details about your environment? Since you're not able to reproduce the issue, we might be doing something wrong on our side.

**Comment by iluwatar** [comment]
https://github.com/iluwatar/java-design-patterns-vuepress-web/pull/99#issuecomment-3866763775
